package com.ranjit.galleryapplication.domain.model

data class Gallery(
    val id: String,
    val title: String,
    val description: String,
    val datetime: Long,
    val coverUrl: String,
    val coverWidth: Int,
    val coverHeight: Int,
    val accountUrl: String,
    val accountId: Int,
    val privacy: String,
    val layout: String,
    val views: Int,
    val link: String,
    val ups: Int,
    val downs: Int,
    val points: Long,
    val score: Long,
    val isAlbum: Boolean,
    val vote: String,
    val favorite: Boolean,
    val nsfw: Boolean,
    val section: String,
    val commentCount: Int,
    val favoriteCount: Int,
    val topic: String,
    val topicId: Int,
    val imagesCount: Int,
    val inGallery: Boolean,
    val isAd: Boolean,
    val adType: Int,
    val adUrl: String,
    val inMostViral: Boolean,
    val includeAlbumAds: Boolean
)